### PR TITLE
Tercio

### PR DESCRIPTION
**Pull request by Lulq**
[luiz.txt](https://github.com/JoaoVictorRocha/Sala4_DigitalHouse/files/6198061/luiz.txt)
Adiciona esse arquivo

### CODE REVIEW

**Comment by JoaoVictorRocha** [comment]
LGTM

**Comment by Lulq** [comment]
GJ

**Comment by stefanigaldino** [comment]
ok

**Comment by elianbalbino** [comment]
Visto

**Comment by JoaoVictorRocha** [comment]
LGTM ²

**Comment by TercioLins** [comment]
ok!

**Pull request merged**
